In [2]:
import pandas as pd
import numpy as np
import sklearn
from sklearn.metrics import mean_squared_error

In [3]:
data=pd.read_csv('randomdata.csv')
data.head()


Fever   Age   BodyPain  DifficultyinBreath  RunnyNose  Travel   Cough  \
0     101   65          1                   0          0        1      1   
1      98   59          0                   1          0        1      1   
2     103   46          0                   1          1        0      0   
3     104   83          0                   0          0        0      1   
4      98   98          0                   0          1        0      0   

   Probability  
0            1  
1            0  
2            0  
3            0  
4            0

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1999 entries, 0 to 1998
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Fever               1999 non-null   int64
 1   Age                 1999 non-null   int64
 2    BodyPain           1999 non-null   int64
 3   DifficultyinBreath  1999 non-null   int64
 4   RunnyNose           1999 non-null   int64
 5   Travel              1999 non-null   int64
 6   Cough               1999 non-null   int64
 7   Probability         1999 non-null   int64
dtypes: int64(8)
memory usage: 125.0 KB


In [8]:
#here we want target to be probability i.e., for y so removing in x therefore except probability other would be the features for (x) in data
x=data.drop('Probability',axis=1)
print(x.head())
print('data in y')
y=data['Probability']
print(y.head())

   Fever   Age   BodyPain  DifficultyinBreath  RunnyNose  Travel   Cough
0     101   65          1                   0          0        1      1
1      98   59          0                   1          0        1      1
2     103   46          0                   1          1        0      0
3     104   83          0                   0          0        0      1
4      98   98          0                   0          1        0      0
data in y
0    1
1    0
2    0
3    0
4    0
Name: Probability, dtype: int64


In [12]:
#splitting the data in train and test set
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.33,random_state=5)

In [15]:
#converting to the numpy array
print(x_train.to_numpy())
y_train.to_numpy()
x_test.to_numpy()
y_test.to_numpy()

[[101  16   1 ...   0   0   1]
 [ 98  25   1 ...   0   0   0]
 [104  53   0 ...   1   1   0]
 ...
 [103  63   0 ...   0   1   1]
 [104  38   1 ...   1   1   1]
 [ 98 100   0 ...   1   1   1]]


array([0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0,
       1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0,
       1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1,
       0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1,
       0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1,
       0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0,

In [16]:
from sklearn.linear_model import LogisticRegression
#loading in clf
clf=LogisticRegression()
#training the podel
#fitting the data
y_train_predict=clf.fit(x_train,y_train)

In [19]:
#prediction
#give values for 7 columns to predict
infection=clf.predict([[98,20,0,1,0,0,0]])
print(infection)
#infection probability
infection_probability=clf.predict_proba([[98,20,0,1,0,0,0]])
print(infection_probability)

[0]
[[0.51724271 0.48275729]]
